# Generated by Django 2.0 on 2018-07-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('shortTitle', models.CharField(default='', max_length=40)),
                ('title', models.CharField(default='', max_length=100)),
                ('abstract', models.CharField(default='', max_length=500)),
                ('body', models.CharField(default='', max_length=10000)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
