# Generated by Django 2.0 on 2018-07-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
